### ISSUE TITLE
How to run the example code? 

### ISSUE THREAD

**Issue by xlcbingo1999** [yomorun/yomo-source-mqtt-broker-starter#26]
My env:
```
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
```
My operation:
1. make a new dir
2. in this new dir, I tried: `go mod init source`
3. I created your first demo `app.go` 
4. `go get` and `go run app.go`

But, I got: 
```
panic: NewClient error:NO_ERROR: Handshake did not complete in time
```

I found there is no quic in `github.com/yomorun/yomo/pkg/quic`;
Where is it?

**Comment by xiaojian-hong** [comment]
Hi @xlcbingo1999 ,

The example code was outdated, the quic package `github.com/yomorun/yomo/pkg/quic` was removed in YoMo's latest version.
We just upgraded the example to latest version, you could checkout the new codes and follow the steps in `README` to run the example.

**Comment by xlcbingo1999** [comment]
Dear @xiaojian-hong ,
Thanks for your help!
